version: '3.1'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./sql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wala_test
    ports:
      - 3306:3306
  backend:
    build:
      context: building-backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
    depends_on:
      - db
  frontend:
    build:
      context: building-frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - db
      - backend
